[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@solmate=lib/solmate/src/',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/'
]
fs_permissions = [{ access = "read", path = "./src" }]
# Exclude problematic vendor files that cause version conflicts
[profile.default.fuzz]
exclude = [
    "lib/chainlink-brownie-contracts/contracts/src/v0.8/vendor/@eth-optimism/**",
    "lib/chainlink-brownie-contracts/contracts/src/v0.8/vendor/@arbitrum/**"
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config